In [1]:
import os
HOME = os.getcwd()
print(HOME)

/home/manidhar/Desktop/AryanWork/yolov8-seg-training


In [2]:
!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
Setup complete ✅ (16 CPUs, 62.6 GB RAM, 223.9/226.3 GB disk)


In [3]:
from ultralytics import YOLO

model = YOLO("Trained Models/segmentation_trained_model.pt")  # loading a trained detection model

In [4]:
print(model.model.names)

{0: 'A-10-TRIDEM', 1: 'A-13', 2: 'AXLE', 3: 'TYPE 2-S2', 4: 'TYPE 3-S2', 5: 'TYPE-2', 6: 'TYPE-3', 7: 'UC'}


In [5]:
result = model("Test_Images/1.jpg")

Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA RTX A4000, 16109MiB)
YOLOv8s-seg summary (fused): 195 layers, 11782696 parameters, 0 gradients, 42.5 GFLOPs


In [71]:
print(result[0].masks.masks[0].cpu().numpy())
print(result[0].boxes.cls)

[[          0           0           0 ...           0           0           0]
 [          0           0           0 ...           0           0           0]
 [          0           0           0 ...           0           0           0]
 ...
 [          0           0           0 ...           0           0           0]
 [          0           0           0 ...           0           0           0]
 [          0           0           0 ...           0           0           0]]
tensor([5., 2., 2.], device='cuda:0')
