In [7]:

def get_actual_mask_from_polygon(file_name_of_label,defined_classes):

    import numpy
    from PIL import Image, ImageDraw

    side_length = 640 
    width = side_length
    height = side_length

    img = Image.new('L', (width, height), 0)

    file = open(file_name_of_label, mode = 'r', encoding = 'utf-8-sig')
    lines = file.readlines()
    file.close()
    

    for line in lines:
        line = line.split(' ')
        line = [i.strip() for i in line]
        class_of_annotation=int(line[0])
        is_in_defined_classes = False

        #checking is annoatation is present in list of defined classes
        for annotation_class in defined_classes:
            if(annotation_class==class_of_annotation):
                is_in_defined_classes=True
        
        if(is_in_defined_classes):
            polygon = []
            for i in range(1,len(line)):
                line[i]=float(line[i])*side_length
                polygon.append(line[i])
            ImageDraw.Draw(img).polygon(polygon, outline=1, fill=1)

    mask = numpy.array(img)
    print(mask)

    return mask

In [8]:
import cv2

filename_of_label = "Test_Images/labels/1.txt"
filename_of_image = "Test_Images/1.jpg"
defined_classes = [0,1,2,3,4,5,6,7]

mask = get_actual_mask_from_polygon(filename_of_label,defined_classes)

img = cv2.imread(filename_of_image)
res = cv2.bitwise_and(img,img,mask = mask)
# cv2.imshow("img",res)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
